import { ScheduleAltName } from './types/scheduleTypes';

const rKey = {
    createAccountLock: (phone: string) => `createAccountLock:${phone}`,
    verificationLock: (phone: string) => `verifications:lock:${phone}`,
    verificationIdFromPhone: (phone: string) => `verifications:verificationIdFromPhone:${phone}`,
    verification: (verificationId: string) => `verifications:verification:${verificationId}`,
    user: (userId: number) => `user:${userId}`,
    userCountry: (userId: number) => `userRequestMeta:country:${userId}`,
    userLastOnline: (userId: number) => `userRequestMeta:lastOnline:${userId}`,
    userRawHeaders: (userId: number) => `userRequestMeta:rawHeaders:${userId}`,
    userTrackedIps: (userId: number) => `userRequestMeta:trackedIps:${userId}`,
    ipToUsers: (ip: string) => `ipToUsers:${ip}`, // Reverse index: IP -> set of user IDs
    friendIds: (userId: number) => `friendIds:${userId}`,
    seasonConfig: 'season:config',
    seasonLevels: 'season:levels',
    questionPoints: 'season:questionPoints',
    puzzlePoints: 'season:puzzlePoints',
    schedule: (type: ScheduleAltName) => `schedule:shows:${type}`,
    scheduleLastEdited: 'schedule:lastEdited',
    announcements: 'schedule:announcements',
    generalConfig: 'generalConfig',
    offairTriviaConfig: 'offairTriviaConfig',
    streakConfig: 'streakConfig',
    keepPlayingConfig: 'keepPlayingConfig',
    opts: 'opts',
    mainConfig: 'config:main',
    publicConfig: 'config:public',
    offairTriviaGameUuid: (userId: number) => `offairTrivia:currentGameUuid:${userId}`,
    offairTriviaGameStatus: (gameUuid: string) => `offairTrivia:gameStatus:${gameUuid}`,
    offairTriviaCooldown: (userId: number) => `offairTrivia:cooldown:${userId}`,
    offairTriviaLock: (userId: number) => `offairTrivia:lock:${userId}`,
    makeItRainClaim: (userId: number) => `makeItRainClaim:${userId}`,
    liveConfig: (envName: string, rehearsal: number) => `liveConfig:${envName}:${rehearsal}`,
    streakInProgress: (userId: number | string) => `streaksInProgress:${userId}`,
    bootStatus: (server: string) => `bootStatus:${server}`,
    bootStreamState: 'bootStream:state', // Stores JSON with dropletId, step, etc.
    employeeCategories: 'ap:categories:names',
    employeeCategoryOrder: 'ap:categories:order',
    schemaMigrations: (name: string) => `schema:migrations:${name}`,
    employeeIds: 'ap:users',
    employee: (employeeIdOrToken: string) => `ap:users:${employeeIdOrToken}`,
    employeeLastOnline: (employeeIdOrToken: string) => `ap:users:lastOnline:${employeeIdOrToken}`,
    employeePermissions: (employeeId: string) => `ap:permissions:${employeeId}`,
    employeeCategoryPermissions: (categorySlug: string) => `ap:categoryPermissions:${categorySlug}`,
    storeProducts: 'store:products',
    userForensics: (userId: number) => `ap:forensics:${userId}`,
    forensicsJobLock: 'ap:forensics:job:lock',
    forensicsJobLastRun: 'ap:forensics:job:lastRun',
    apGame: (gameId: string) => `ap:game:${gameId}`,
    apGameAll: 'ap:game:all',
    apGameSchedule: (gameId: string) => `ap:game:schedule:${gameId}`,
    apGameProduction: (gameId: string) => `ap:game:production:${gameId}`,
    apGameBroadcast: (gameId: string) => `ap:game:broadcast:${gameId}`,
    apGameWins: (gameId: string) => `ap:game:wins:${gameId}`,
    gameOutline: (gameId: number) => `game:outline:${gameId}`,
    triviaGameMeta: (gameId: string) => `game:meta:trivia:${gameId}`,
    wordsGameMeta: (gameId: string) => `game:meta:words:${gameId}`,
    superWheelItems: 'game:superWheelItems',
    broadcast: (broadcastId: number) => `broadcast:${broadcastId}`,
    producerConnCount: 'ws:producerConnCount',
}

export default rKey;
